# Generated by Django 3.1.7 on 2021-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0002_auto_20210224_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamestats',
            options={'verbose_name_plural': "Gamestats's"},
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='number_scrabbles',
            field=models.IntegerField(choices=[(1, 'Un'), (2, 'Deux'), (3, 'Trois'), (4, 'Quatre'), (5, 'Cinq'), (6, 'Six'), (7, 'Sept'), (8, 'Huit'), (9, 'Neuf'), (10, 'Dix')]),
        ),
    ]
