# Generated by Django 3.1.7 on 2021-02-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0004_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='comments',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
