# Generated by Django 3.1.7 on 2021-02-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0005_auto_20210225_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='comments',
            new_name='commentaires',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='gagnant',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='place',
            new_name='lieu',
        ),
        migrations.RenameField(
            model_name='gamestats',
            old_name='player',
            new_name='joueur',
        ),
        migrations.RenameField(
            model_name='gamestats',
            old_name='number_scrabbles',
            new_name='nombre_scrabbles',
        ),
        migrations.RenameField(
            model_name='gamestats',
            old_name='game',
            new_name='partie',
        ),
    ]
