# Generated by Django 3.1.7 on 2021-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0006_auto_20210225_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nombre_joueurs',
            field=models.IntegerField(default=2),
        ),
    ]
