# Generated by Django 3.1.7 on 2021-02-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0007_game_nombre_joueurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='nom',
        ),
    ]
