# Generated by Django 3.1.7 on 2021-02-25 09:47

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0010_auto_20210225_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=datetime.date(2021, 2, 25)),
        ),
        migrations.AlterField(
            model_name='game',
            name='heure',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
