# Generated by Django 3.1.7 on 2021-02-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0012_auto_20210225_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='nombre_joueurs',
        ),
        migrations.AlterField(
            model_name='game',
            name='commentaires',
            field=models.TextField(blank=True, default='No comments', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='gagnant',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrabble.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamestats',
            name='nombre_scrabbles',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'Un'), (2, 'Deux'), (3, 'Trois'), (4, 'Quatre'), (5, 'Cinq'), (6, 'Six'), (7, 'Sept'), (8, 'Huit'), (9, 'Neuf'), (10, 'Dix')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='nom',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nom du joueur'),
        ),
    ]
