# Generated by Django 3.1.7 on 2021-02-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0014_auto_20210226_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gagnant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scrabble.player'),
        ),
    ]
