# Generated by Django 3.1.7 on 2021-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0016_auto_20210226_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nombre_joueurs',
            field=models.IntegerField(default=2),
        ),
    ]
