# Generated by Django 3.1.7 on 2021-02-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble', '0017_game_nombre_joueurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='nombre_joueurs',
        ),
    ]
